### PR TITLE
Update runtime to 5.15-21.08

### PR DESCRIPTION
**Pull request by hfiguiere**
- remove unused manifest files
- update some modules, ~~now require Rust to build cryptography~~ (cryptography update isn't happening)
  - llfuse 1.37 doesn't build out of the box
  - borgbackup is to latest 1.1.17

### CODE REVIEW

**Comment by hfiguiere** [comment]
Currently fail to run with:

```
ImportError: cannot import name '_bcrypt' from partially initialized module 'bcrypt' (most likely due to a circular import) (/app/lib/python3.9/site-packages/bcrypt/__init__.py)
```

**Comment by hfiguiere** [comment]
Currently spawn that error:

```
2021-12-19 19:55:24,863 - vorta.borg.borg_job - INFO - Running command /app/bin/borg --version
2021-12-19 19:55:25,182 - vorta.borg.borg_job - WARNING - Traceback (most recent call last):
2021-12-19 19:55:25,182 - vorta.borg.borg_job - WARNING - File "/app/lib/python3.9/site-packages/borg/archiver.py", line 82, in <module>
2021-12-19 19:55:25,183 - vorta.borg.borg_job - WARNING - from .selftest import selftest
2021-12-19 19:55:25,185 - vorta.borg.borg_job - WARNING - File "/app/lib/python3.9/site-packages/borg/selftest.py", line 20, in <module>
2021-12-19 19:55:25,186 - vorta.borg.borg_job - WARNING - from .testsuite.hashindex import HashIndexDataTestCase, HashIndexRefcountingTestCase, HashIndexTestCase
2021-12-19 19:55:25,188 - vorta.borg.borg_job - WARNING - File "/app/lib/python3.9/site-packages/borg/testsuite/__init__.py", line 25, in <module>
2021-12-19 19:55:25,193 - vorta.borg.borg_job - WARNING - have_fuse_mtime_ns = hasattr(llfuse.EntryAttributes, 'st_mtime_ns')
2021-12-19 19:55:25,193 - vorta.borg.borg_job - WARNING - AttributeError: module 'llfuse' has no attribute 'EntryAttributes'
```

**Comment by Hofer-Julian** [comment]
@hfiguiere thanks for working on this.
As you've seen, I've also spent a weekend on this.

Maybe we can get it working together, in my case it will have to wait till after the holidays.

**Comment by hfiguiere** [comment]
I won't have much time after.

**Comment by Hofer-Julian** [comment]
I've extended the branch.
Now everything seems to work, but the gui looks a bit weird

image

**Comment by hfiguiere** [comment]
works fine here. I assume the black boxes are your doing ti "anonymize" the screen though. Because I don't have them here.

**Comment by Hofer-Julian** [comment]
> works fine here. I assume the black boxes are your doing ti "anonymize" the screen though. Because I don't have them here.

Yep, but e. g. the tabs shouldn't be aligned to the left, but centered and fill the space.

Also the subtabs are not rendered.

**Comment by hfiguiere** [comment]
the 5.15 runtime is EOL.

**Pull request merged**
