### PR TITLE
Revert "Update runtime to KDE 5.15"

### PR DESCRIPTION
**Pull request by samuel-w**
Fixes https://github.com/borgbase/vorta/issues/775, somehow. Wait for the test build.

### CODE REVIEW

**Comment by Hofer-Julian** [comment]
Okay, this sucks....
Still, let me know, when I should merge it.

**Comment by carobinario** [comment]
> Build [38225 successful](https://flathub.org/builds/#/builders/32/builds/38225)
> To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/36812/com.borgbase.Vorta.flatpakref
> ```

Tested in Manjaro running in Virtualbox. Everything is fine, the bug is solved. Thanks.

_Operating System: Manjaro Linux
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2
Kernel Version: 5.9.16-1-MANJARO
OS Type: 64-bit
Processors: 2 × Intel® Core™ i5-6600 CPU @ 3.30GHz
Memory: 7.6 GiB of RAM
Graphics Processor: llvmpipe_

**Comment by samuel-w** [comment]
Closing in favour of https://github.com/borgbase/vorta/pull/778

**Comment by samuel-w** [comment]
Might want to temporarily merge this, then revert it next update.

**Comment by Hofer-Julian** [comment]
Sure

**Pull request merged**
