### PR TITLE
Add --filesystem=~/.var/app/ to complete home dir

### PR DESCRIPTION
**Pull request by samuel-w**
Inspired by https://gitlab.gnome.org/World/pika-backup/-/issues/39 fix.

Fixes https://github.com/borgbase/vorta/issues/652

### CODE REVIEW

**Comment by Hofer-Julian** [comment]
I saw the MR, but I don't really understand what this changes

**Comment by samuel-w** [comment]
It adds the ~/.var/app folder permission, allowing other flatpak application settings to be backed up.

**Comment by samuel-w** [comment]
It's the workaround for https://github.com/borgbase/vorta/issues/544.

**Comment by samuel-w** [comment]
Wonder if there is a way to synchronize files here and in borgbase/vorta, otherwise there will need to be another PR for every change that affects flatapk.

**Comment by Hofer-Julian** [comment]
So, you tested that after this change the other flatpak data is backed up as well?

**Comment by Hofer-Julian** [comment]
Yeah, that is annoying, but currently I see no alternative...

**Comment by samuel-w** [comment]
I tested it, and it does start to backup the entire org.gnome.builder directory, so it seems to work

**Comment by Hofer-Julian** [comment]
Huh fascinating...
I have to ask flatpak gurus at some point why that is so. 

I expected that host covers everything possible

**Comment by Hofer-Julian** [comment]
By the way, do you want to co-maintain this repo?

**Comment by samuel-w** [comment]
We could make this repo a submodule in the main repo, but it would only compile the tag.

**Comment by Hofer-Julian** [comment]
Yeah, but submodules are a pain. Only few contributors will know how to properly use them.

**Pull request merged**
