### PR TITLE
Drop kde own name

### PR DESCRIPTION
**Pull request by bbhtt**

### CODE REVIEW

**Comment by Hofer-Julian** [comment]
Last time I've checked, this was needed for the tray icon.
Did you test this change?

**Comment by bbhtt** [comment]
>  Did you test this change also on GNOME based distros like Ubuntu?

No, will do, give me some time.

**Comment by bbhtt** [comment]
Works on F39 beta with the appindicator extension, will test in a KDE neon vm

**Comment by bbhtt** [comment]
Works on F39 beta with the appindicator extension, and on KDE neon VM too

image


image

**Comment by Hofer-Julian** [comment]
Thanks for checking @bbhtt!
Always good to close holes in the sandbox

**Pull request merged**
